"""
Role catalog and ordering for platform and tenant staff access.
"""

from __future__ import annotations

PLATFORM_ROLE_NAMES = {"super_manager", "developer_admin"}
TENANT_ADMIN_ROLE_NAME = "tenant_admin"
COMPLIANCE_NOTIFICATION_ROLES = {
    "super_manager",
    "developer_admin",
    "tenant_admin",
    "director",
    "compliance_officer",
    "finance_officer",
}

ROLE_DEFINITIONS = [
    {"name": "super_manager", "description": "Full platform control across every tenant, catalog, billing flow, and system setting."},
    {"name": "developer_admin", "description": "Platform tenancy, plans, modules, onboarding, and billing administration."},
    {"name": "tenant_admin", "description": "Full tenant administration including staff registration, settings, reports, and operational oversight."},
    {"name": "director", "description": "Executive oversight for finance, sales, compliance, staffing, and management reporting."},
    {"name": "farm_manager", "description": "Farm leadership for houses, flocks, feeding, health records, and daily production control."},
    {"name": "operations_officer", "description": "Daily operations execution across farm activities, feed usage, processing, and inventory handoff."},
    {"name": "production_officer", "description": "Production run capture, yield tracking, cut-part recording, and output inventory updates."},
    {"name": "slaughter_supervisor", "description": "Slaughter scheduling, record capture, yield approval, and processed output posting."},
    {"name": "veterinary_officer", "description": "Bird health, vaccination, medication, mortality follow-up, and welfare monitoring."},
    {"name": "inventory_officer", "description": "Feed, medicine, and stock control including receipts, balances, and stock movements."},
    {"name": "procurement_officer", "description": "Supplier coordination, replenishment planning, and stock availability monitoring."},
    {"name": "sales_officer", "description": "Customers, orders, invoicing, dispatch coordination, and sales follow-up."},
    {"name": "cashier", "description": "Cash collection, payment posting, receipt handling, and day-to-day sales settlement."},
    {"name": "finance_officer", "description": "Expenses, income, payment controls, and financial reporting for the tenant."},
    {"name": "compliance_officer", "description": "Compliance documents, expiry follow-up, renewal coordination, and audit readiness."},
    {"name": "support_staff", "description": "Restricted operational support access for supervised day-to-day assistance tasks."},
]

ROLE_DISPLAY_ORDER = [role["name"] for role in ROLE_DEFINITIONS]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_manager": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "farm:delete",
        "feed:read",
        "feed:write",
        "feed:delete",
        "slaughter:read",
        "slaughter:write",
        "slaughter:delete",
        "inventory:read",
        "inventory:write",
        "inventory:delete",
        "sales:read",
        "sales:write",
        "sales:delete",
        "finance:read",
        "finance:write",
        "finance:delete",
        "reports:read",
        "reports:export",
        "settings:read",
        "settings:write",
        "users:read",
        "users:write",
        "users:delete",
        "dev_admin:read",
        "dev_admin:write",
    ],
    "developer_admin": [
        "dashboard:read",
        "reports:read",
        "users:read",
        "dev_admin:read",
        "dev_admin:write",
    ],
    "tenant_admin": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "farm:delete",
        "feed:read",
        "feed:write",
        "feed:delete",
        "slaughter:read",
        "slaughter:write",
        "slaughter:delete",
        "inventory:read",
        "inventory:write",
        "inventory:delete",
        "sales:read",
        "sales:write",
        "sales:delete",
        "finance:read",
        "finance:write",
        "finance:delete",
        "reports:read",
        "reports:export",
        "settings:read",
        "settings:write",
        "users:read",
        "users:write",
        "users:delete",
    ],
    "director": [
        "dashboard:read",
        "farm:read",
        "feed:read",
        "slaughter:read",
        "inventory:read",
        "sales:read",
        "finance:read",
        "reports:read",
        "reports:export",
        "settings:read",
        "users:read",
        "users:write",
    ],
    "farm_manager": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "feed:read",
        "feed:write",
        "inventory:read",
        "reports:read",
    ],
    "operations_officer": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "feed:read",
        "feed:write",
        "slaughter:read",
        "slaughter:write",
        "inventory:read",
        "reports:read",
    ],
    "production_officer": [
        "dashboard:read",
        "farm:read",
        "feed:read",
        "slaughter:read",
        "slaughter:write",
        "inventory:read",
        "inventory:write",
        "reports:read",
    ],
    "slaughter_supervisor": [
        "dashboard:read",
        "slaughter:read",
        "slaughter:write",
        "inventory:read",
        "inventory:write",
        "reports:read",
    ],
    "veterinary_officer": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "feed:read",
        "reports:read",
    ],
    "inventory_officer": [
        "dashboard:read",
        "inventory:read",
        "inventory:write",
        "inventory:delete",
        "feed:read",
        "feed:write",
        "sales:read",
        "reports:read",
    ],
    "procurement_officer": [
        "dashboard:read",
        "inventory:read",
        "inventory:write",
        "feed:read",
        "feed:write",
        "finance:read",
        "reports:read",
    ],
    "sales_officer": [
        "dashboard:read",
        "sales:read",
        "sales:write",
        "sales:delete",
        "inventory:read",
        "reports:read",
    ],
    "cashier": [
        "dashboard:read",
        "sales:read",
        "sales:write",
        "finance:read",
        "finance:write",
        "reports:read",
    ],
    "finance_officer": [
        "dashboard:read",
        "finance:read",
        "finance:write",
        "finance:delete",
        "sales:read",
        "reports:read",
        "reports:export",
        "settings:read",
    ],
    "compliance_officer": [
        "dashboard:read",
        "farm:read",
        "farm:write",
        "reports:read",
        "settings:read",
    ],
    "support_staff": [
        "dashboard:read",
        "farm:read",
        "feed:read",
        "inventory:read",
    ],
}


def role_sort_key(role_name: str) -> tuple[int, str]:
    try:
        return (ROLE_DISPLAY_ORDER.index(role_name), role_name)
    except ValueError:
        return (len(ROLE_DISPLAY_ORDER), role_name)
