"""
Models package — imports all models so Alembic can detect them.
"""

from app.db.base import Base  # noqa: F401
from app.models.auth import Role, Permission, RolePermission, RefreshToken, AuditLog  # noqa: F401
from app.models.compliance import ComplianceDocument, DocumentReminder  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.farm import (  # noqa: F401
    PoultryHouse,
    PoultryHouseSection,
    Batch,
    MortalityLog,
    VaccinationLog,
    GrowthLog,
    MedicationAdministration,
)
from app.models.feed import (  # noqa: F401
    Supplier,
    SupplierItemPrice,
    FeedCategory,
    FeedItem,
    FeedPurchase,
    FeedPurchaseItem,
    FeedConsumption,
    FeedFormulation,
    FeedFormulationIngredient,
    FeedProductionBatch,
)
from app.models.inventory import (  # noqa: F401
    StockItem,
    StockMovement,
    StockTransfer,
    StoreLocation,
    GoodsIssueVoucher,
    GoodsReceivedNote,
)
from app.models.slaughter import SlaughterRecord, SlaughterOutput, SlaughterByProduct  # noqa: F401
from app.models.sales import Customer, Invoice, InvoiceBalanceReminder, Order, OrderItem, Payment  # noqa: F401
from app.models.finance import ExpenseCategory, Expense, IncomeCategory, Income  # noqa: F401
from app.models.finance_coa import (  # noqa: F401
    Account, AccountTemplate, TemplateAccount,
    FiscalYear, OpeningBalance,
    JournalEntry, JournalLine,
    AccountType, NormalBalance, JournalEntryStatus, FiscalYearStatus,
)
from app.models.safety import IncidentReport, SafetyInspection, SafetyInspectionItem, CorrectiveAction  # noqa: F401
from app.models.settings import EmailLog, MasterDataRequest, ProductCatalog, ReferenceItem, SystemConfig, SystemSettings  # noqa: F401
from app.models.egg_production import EggProductionLog  # noqa: F401
from app.models.affiliate import (  # noqa: F401
    Affiliate,
    AffiliateActivityLog,
    AffiliateCommission,
    AffiliateCommissionRule,
    AffiliateReferral,
)
from app.models.tenant import (  # noqa: F401
    BillingInvoice,
    BillingPayment,
    DomainRequestStatus,
    Tenant,
    TenantDomainRequest,
    TenantDomainRequestMessage,
    TenantModule,
    TenantModuleRequest,
    TenantModuleRequestItem,
    SubscriptionHistory,
    PlatformModule,
    PlanDefinition,
    PlanModule,
    TenantDomain,
    Subscription,
    PaymentCallbackLog,
)
from app.models.branch import Branch, UserBranchAccess  # noqa: F401
from app.models.branch_transfer import BranchTransfer, BranchTransferItem, TransferStatus  # noqa: F401
from app.models.hr import Employee, PayrollPeriod, PayrollLine, LeaveType, LeaveRequest, AttendanceRecord  # noqa: F401
from app.models.procurement import (  # noqa: F401
    PurchaseOrder,
    PurchaseOrderItem,
    SupplierInvoice,
    SupplierPayment,
    POStatus,
    SupplierInvoiceStatus,
    SupplierPaymentMethod,
)

__all__ = [
    "Base",
    "Role",
    "Permission",
    "RolePermission",
    "RefreshToken",
    "AuditLog",
    "ComplianceDocument",
    "DocumentReminder",
    "User",
    "PoultryHouse",
    "PoultryHouseSection",
    "Batch",
    "MortalityLog",
    "VaccinationLog",
    "GrowthLog",
    "Supplier",
    "SupplierItemPrice",
    "FeedCategory",
    "FeedItem",
    "FeedPurchase",
    "FeedPurchaseItem",
    "FeedConsumption",
    "FeedFormulation",
    "FeedFormulationIngredient",
    "FeedProductionBatch",
    "StockItem",
    "StockMovement",
    "StockTransfer",
    "SlaughterRecord",
    "SlaughterOutput",
    "SlaughterByProduct",
    "Customer",
    "Order",
    "OrderItem",
    "Invoice",
    "InvoiceBalanceReminder",
    "Payment",
    "ExpenseCategory",
    "Expense",
    "IncomeCategory",
    "Income",
    "Account",
    "AccountTemplate",
    "TemplateAccount",
    "FiscalYear",
    "OpeningBalance",
    "JournalEntry",
    "JournalLine",
    "IncidentReport",
    "SafetyInspection",
    "SafetyInspectionItem",
    "CorrectiveAction",
    "ProductCatalog",
    "ReferenceItem",
    "SystemConfig",
    "SystemSettings",
    "EmailLog",
    "MasterDataRequest",
    "EggProductionLog",
    "Affiliate",
    "AffiliateActivityLog",
    "AffiliateCommission",
    "AffiliateCommissionRule",
    "AffiliateReferral",
    "BillingInvoice",
    "BillingPayment",
    "DomainRequestStatus",
    "Tenant",
    "TenantDomainRequest",
    "TenantDomainRequestMessage",
    "TenantModule",
    "TenantModuleRequest",
    "TenantModuleRequestItem",
    "SubscriptionHistory",
    "PlatformModule",
    "PlanDefinition",
    "PlanModule",
    "TenantDomain",
    "Subscription",
    "ModulePrice",
    "PaymentCallbackLog",
    "StoreLocation",
    "GoodsIssueVoucher",
    "GoodsReceivedNote",
    "MedicationAdministration",
    "Branch",
    "UserBranchAccess",
    "BranchTransfer",
    "BranchTransferItem",
    "Employee",
    "PayrollPeriod",
    "PayrollLine",
    "LeaveType",
    "LeaveRequest",
    "AttendanceRecord",
    "PurchaseOrder",
    "PurchaseOrderItem",
    "SupplierInvoice",
    "SupplierPayment",
]
