"""auto_fix_out_of_sync_columns

Revision ID: 5aff6d31f520
Revises: 026
Create Date: 2026-06-12 07:51:13.414422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aff6d31f520'
down_revision = '026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('from_branch_id', sa.Integer(), nullable=False),
    sa.Column('to_branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.dialects.postgresql.ENUM('pending', 'in_transit', 'completed', 'rejected', 'cancelled', name='transferstatus', create_type=False), nullable=False),
    sa.Column('initiated_by_id', sa.Integer(), nullable=True),
    sa.Column('dispatched_by_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receive_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dispatched_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number', 'tenant_id', name='uq_transfer_number_tenant')
    )
    op.create_index(op.f('ix_branch_transfers_from_branch_id'), 'branch_transfers', ['from_branch_id'], unique=False)
    op.create_index(op.f('ix_branch_transfers_id'), 'branch_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_branch_transfers_tenant_id'), 'branch_transfers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_branch_transfers_to_branch_id'), 'branch_transfers', ['to_branch_id'], unique=False)
    op.create_index(op.f('ix_branch_transfers_transfer_number'), 'branch_transfers', ['transfer_number'], unique=False)
    op.create_table('branch_transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_shipped', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['branch_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_transfer_items_id'), 'branch_transfer_items', ['id'], unique=False)
    op.create_index(op.f('ix_branch_transfer_items_transfer_id'), 'branch_transfer_items', ['transfer_id'], unique=False)
    op.add_column('batches', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_batches_branch_id'), 'batches', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'batches', 'branches', ['branch_id'], ['id'])
    op.add_column('feed_production_batches', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_feed_production_batches_branch_id'), 'feed_production_batches', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'feed_production_batches', 'branches', ['branch_id'], ['id'])
    op.add_column('feed_purchases', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_feed_purchases_branch_id'), 'feed_purchases', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'feed_purchases', 'branches', ['branch_id'], ['id'])
    op.drop_index('idx_invoices_customer_status', table_name='invoices')
    op.drop_index('idx_payments_invoice', table_name='payments')
    op.add_column('poultry_houses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_poultry_houses_branch_id'), 'poultry_houses', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'poultry_houses', 'branches', ['branch_id'], ['id'])
    op.add_column('stock_items', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_items_branch_id'), 'stock_items', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'stock_items', 'branches', ['branch_id'], ['id'])
    op.add_column('stock_movements', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_branch_id'), 'stock_movements', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'branches', ['branch_id'], ['id'])
    op.add_column('store_locations', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_store_locations_branch_id'), 'store_locations', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'store_locations', 'branches', ['branch_id'], ['id'])
    op.add_column('suppliers', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_branch_id'), 'suppliers', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'branches', ['branch_id'], ['id'])
    op.create_index(op.f('ix_user_branch_access_branch_id'), 'user_branch_access', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_branch_access_tenant_id'), 'user_branch_access', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_branch_access_user_id'), 'user_branch_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_branch_access_user_id'), table_name='user_branch_access')
    op.drop_index(op.f('ix_user_branch_access_tenant_id'), table_name='user_branch_access')
    op.drop_index(op.f('ix_user_branch_access_branch_id'), table_name='user_branch_access')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_branch_id'), table_name='suppliers')
    op.drop_column('suppliers', 'branch_id')
    op.drop_constraint(None, 'store_locations', type_='foreignkey')
    op.drop_index(op.f('ix_store_locations_branch_id'), table_name='store_locations')
    op.drop_column('store_locations', 'branch_id')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_branch_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'branch_id')
    op.drop_constraint(None, 'stock_items', type_='foreignkey')
    op.drop_index(op.f('ix_stock_items_branch_id'), table_name='stock_items')
    op.drop_column('stock_items', 'branch_id')
    op.drop_constraint(None, 'poultry_houses', type_='foreignkey')
    op.drop_index(op.f('ix_poultry_houses_branch_id'), table_name='poultry_houses')
    op.drop_column('poultry_houses', 'branch_id')
    op.create_index('idx_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.create_index('idx_invoices_customer_status', 'invoices', ['customer_id', 'status', 'created_at'], unique=False)
    op.drop_constraint(None, 'feed_purchases', type_='foreignkey')
    op.drop_index(op.f('ix_feed_purchases_branch_id'), table_name='feed_purchases')
    op.drop_column('feed_purchases', 'branch_id')
    op.drop_constraint(None, 'feed_production_batches', type_='foreignkey')
    op.drop_index(op.f('ix_feed_production_batches_branch_id'), table_name='feed_production_batches')
    op.drop_column('feed_production_batches', 'branch_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_branch_id'), table_name='batches')
    op.drop_column('batches', 'branch_id')
    op.drop_index(op.f('ix_branch_transfer_items_transfer_id'), table_name='branch_transfer_items')
    op.drop_index(op.f('ix_branch_transfer_items_id'), table_name='branch_transfer_items')
    op.drop_table('branch_transfer_items')
    op.drop_index(op.f('ix_branch_transfers_transfer_number'), table_name='branch_transfers')
    op.drop_index(op.f('ix_branch_transfers_to_branch_id'), table_name='branch_transfers')
    op.drop_index(op.f('ix_branch_transfers_tenant_id'), table_name='branch_transfers')
    op.drop_index(op.f('ix_branch_transfers_id'), table_name='branch_transfers')
    op.drop_index(op.f('ix_branch_transfers_from_branch_id'), table_name='branch_transfers')
    op.drop_table('branch_transfers')
    # ### end Alembic commands ###
