"""Phase 4 - Add batch_id to inventory and sales

Revision ID: 741a8157bf9c
Revises: 023
Create Date: 2026-06-10 12:53:59.829030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741a8157bf9c'
down_revision = '023'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_invoices_batches', 'invoices', 'batches', ['batch_id'], ['id'])
    
    op.add_column('order_items', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_order_items_batches', 'order_items', 'batches', ['batch_id'], ['id'])
    
    op.add_column('orders', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_batches', 'orders', 'batches', ['batch_id'], ['id'])
    
    op.add_column('stock_movements', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.create_foreign_key('fk_stock_movements_batches', 'stock_movements', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stock_movements_batches', 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'batch_id')
    
    op.drop_constraint('fk_orders_batches', 'orders', type_='foreignkey')
    op.drop_column('orders', 'batch_id')
    
    op.drop_constraint('fk_order_items_batches', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'batch_id')
    
    op.drop_constraint('fk_invoices_batches', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'batch_id')
    # ### end Alembic commands ###
