"""enterprise_accounting_foundation

Revision ID: 7a6ece0657b6
Revises: 022
Create Date: 2026-06-09 17:59:24.787806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a6ece0657b6'
down_revision = '022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # deliverystatus is used in an ALTER COLUMN below but was never created
    # by earlier migrations (they used VARCHAR). Create it only if missing.
    conn = op.get_bind()
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'deliverystatus') THEN
                CREATE TYPE deliverystatus AS ENUM ('pending', 'in_transit', 'delivered', 'cancelled');
            END IF;
        END $$;
    """))
    # op.alter_column cannot cast VARCHAR → enum when a default exists.
    # Must drop the default, alter the type, then restore it as the enum default.
    conn.execute(sa.text("ALTER TABLE delivery_notes ALTER COLUMN status DROP DEFAULT"))
    conn.execute(sa.text(
        "ALTER TABLE delivery_notes ALTER COLUMN status TYPE deliverystatus "
        "USING status::text::deliverystatus"
    ))
    conn.execute(sa.text("ALTER TABLE delivery_notes ALTER COLUMN status SET DEFAULT 'pending'::deliverystatus"))
    # ### commands auto generated by Alembic - please adjust! ###
    # Create branches table (required by migration 023 which adds FK to journal_entries)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('head_office', 'farm', 'hatchery', 'processing_plant', 'retail', 'warehouse', name='branchtype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_code', 'tenant_id', name='uq_branch_code_tenant'),
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_branch_code'), 'branches', ['branch_code'], unique=False)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('user_branch_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'branch_id', name='uq_user_branch_access'),
    )
    op.create_index(op.f('ix_user_branch_access_id'), 'user_branch_access', ['id'], unique=False)
    op.create_table('account_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_templates_id'), 'account_templates', ['id'], unique=False)
    op.create_index(op.f('ix_account_templates_name'), 'account_templates', ['name'], unique=True)
    op.create_table('feed_formulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('texture', sa.String(length=50), nullable=False),
    sa.Column('output_quantity_kg', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_formulations_name'), 'feed_formulations', ['name'], unique=True)
    op.create_index(op.f('ix_feed_formulations_stage'), 'feed_formulations', ['stage'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', 'cost_of_sales', name='accounttype'), nullable=False),
    sa.Column('normal_balance', sa.Enum('debit', 'credit', name='normalbalance'), nullable=False),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_manual_entries', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code', 'tenant_id', name='uq_account_code_tenant')
    )
    op.create_index(op.f('ix_accounts_account_code'), 'accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'locked', name='fiscalyearstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_years_id'), 'fiscal_years', ['id'], unique=False)
    op.create_index(op.f('ix_fiscal_years_tenant_id'), 'fiscal_years', ['tenant_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.Enum('giv', 'grn', name='transfertype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=False),
    sa.Column('to_location', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'received', 'cancelled', name='transferstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_reference_number'), 'stock_transfers', ['reference_number'], unique=True)
    op.create_table('template_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', 'cost_of_sales', name='accounttype'), nullable=False),
    sa.Column('normal_balance', sa.Enum('debit', 'credit', name='normalbalance'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_manual_entries', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['account_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_accounts_id'), 'template_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_template_accounts_template_id'), 'template_accounts', ['template_id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'overdue', name='actionstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_id'), 'corrective_actions', ['id'], unique=False)
    op.create_table('feed_formulation_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulation_id', sa.Integer(), nullable=False),
    sa.Column('feed_item_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feed_items.id'], ),
    sa.ForeignKeyConstraint(['formulation_id'], ['feed_formulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_formulation_ingredients_formulation_id'), 'feed_formulation_ingredients', ['formulation_id'], unique=False)
    op.create_table('feed_production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=False),
    sa.Column('formulation_id', sa.Integer(), nullable=False),
    sa.Column('output_item_id', sa.Integer(), nullable=False),
    sa.Column('output_quantity_kg', sa.Float(), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formulation_id'], ['feed_formulations.id'], ),
    sa.ForeignKeyConstraint(['output_item_id'], ['feed_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_production_batches_batch_number'), 'feed_production_batches', ['batch_number'], unique=True)
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_number', sa.String(length=50), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_type', sa.Enum('injury', 'accident', 'biosecurity_breach', 'hazard', 'other', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severitylevel'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reported', 'under_investigation', 'resolved', 'closed', name='incidentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_id'), 'incident_reports', ['id'], unique=False)
    op.create_index(op.f('ix_incident_reports_incident_number'), 'incident_reports', ['incident_number'], unique=True)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('entry_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'posted', 'cancelled', name='journalentrystatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('master_data_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=80), nullable=False),
    sa.Column('suggested_name', sa.String(length=180), nullable=False),
    sa.Column('source_module', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_data_requests_id'), 'master_data_requests', ['id'], unique=False)
    op.create_index(op.f('ix_master_data_requests_request_type'), 'master_data_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_master_data_requests_status'), 'master_data_requests', ['status'], unique=False)
    op.create_table('opening_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('opening_debit', sa.Float(), nullable=False),
    sa.Column('opening_credit', sa.Float(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_balances_account_id'), 'opening_balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_opening_balances_fiscal_year_id'), 'opening_balances', ['fiscal_year_id'], unique=False)
    op.create_index(op.f('ix_opening_balances_id'), 'opening_balances', ['id'], unique=False)
    op.create_index(op.f('ix_opening_balances_tenant_id'), 'opening_balances', ['tenant_id'], unique=False)
    op.create_table('safety_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sa.String(length=50), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspection_type', sa.Enum('ppe', 'sanitation', 'biosecurity', 'general', name='inspectiontype'), nullable=False),
    sa.Column('inspected_by_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'cancelled', name='inspectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspected_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_inspections_id'), 'safety_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_safety_inspections_inspection_number'), 'safety_inspections', ['inspection_number'], unique=True)
    op.create_table('invoice_balance_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=40), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_balance_reminders_customer_id'), 'invoice_balance_reminders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_balance_reminders_id'), 'invoice_balance_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_balance_reminders_invoice_id'), 'invoice_balance_reminders', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_balance_reminders_reminder_type'), 'invoice_balance_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_invoice_balance_reminders_scheduled_for'), 'invoice_balance_reminders', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_invoice_balance_reminders_status'), 'invoice_balance_reminders', ['status'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_id'), 'journal_lines', ['id'], unique=False)
    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('medicine_item_id', sa.Integer(), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('administration_method', sa.String(length=50), nullable=False),
    sa.Column('dosage_per_bird', sa.Float(), nullable=True),
    sa.Column('total_quantity_used', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('birds_treated', sa.Integer(), nullable=False),
    sa.Column('administered_by_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['administered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['medicine_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_administrations_batch_id'), 'medication_administrations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_medication_administrations_medicine_item_id'), 'medication_administrations', ['medicine_item_id'], unique=False)
    op.create_table('safety_inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('safety_inspection_id', sa.Integer(), nullable=False),
    sa.Column('check_item', sa.String(length=200), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', 'na', name='inspectionresult'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['safety_inspection_id'], ['safety_inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_inspection_items_id'), 'safety_inspection_items', ['id'], unique=False)
    op.alter_column('affiliates', 'approved_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('billing_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('billing_invoices_request_id_key', 'billing_invoices', type_='unique')
    op.drop_constraint('uq_billing_invoices_invoice_number', 'billing_invoices', type_='unique')
    op.create_index(op.f('ix_billing_invoices_invoice_number'), 'billing_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_billing_invoices_request_id'), 'billing_invoices', ['request_id'], unique=True)
    op.alter_column('billing_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_compliance_documents_document_type'), 'compliance_documents', ['document_type'], unique=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.alter_column('delivery_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_delivery_notes_customer_id', table_name='delivery_notes')
    op.drop_index('ix_delivery_notes_order_id', table_name='delivery_notes')
    op.drop_index('ix_delivery_notes_status', table_name='delivery_notes')
    op.create_index(op.f('ix_delivery_notes_id'), 'delivery_notes', ['id'], unique=False)
    op.alter_column('document_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_document_reminders_document_id'), 'document_reminders', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_reminders_status'), 'document_reminders', ['status'], unique=False)
    op.drop_column('egg_production_logs', 'created_at')
    op.drop_column('egg_production_logs', 'updated_at')
    op.drop_constraint('expense_categories_name_key', 'expense_categories', type_='unique')
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goods_issue_vouchers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('goods_issue_vouchers', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'from_store_location_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'issued_by_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'approved_by_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('goods_issue_vouchers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_giv_number', 'goods_issue_vouchers', type_='unique')
    op.drop_index('ix_goods_issue_vouchers_giv_number', table_name='goods_issue_vouchers')
    op.create_index(op.f('ix_goods_issue_vouchers_giv_number'), 'goods_issue_vouchers', ['giv_number'], unique=True)
    op.drop_constraint('goods_issue_vouchers_from_store_location_id_fkey', 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint('goods_issue_vouchers_approved_by_id_fkey', 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint('goods_issue_vouchers_issued_by_id_fkey', 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint('goods_issue_vouchers_item_id_fkey', 'goods_issue_vouchers', type_='foreignkey')
    op.create_foreign_key(None, 'goods_issue_vouchers', 'stock_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'goods_issue_vouchers', 'store_locations', ['from_store_location_id'], ['id'])
    op.create_foreign_key(None, 'goods_issue_vouchers', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(None, 'goods_issue_vouchers', 'users', ['issued_by_id'], ['id'])
    op.alter_column('goods_received_notes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('goods_received_notes', 'item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'received_into_store_location_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'received_by_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'approved_by_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('goods_received_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_grn_number', 'goods_received_notes', type_='unique')
    op.drop_index('ix_goods_received_notes_grn_number', table_name='goods_received_notes')
    op.create_index(op.f('ix_goods_received_notes_grn_number'), 'goods_received_notes', ['grn_number'], unique=True)
    op.drop_constraint('goods_received_notes_item_id_fkey', 'goods_received_notes', type_='foreignkey')
    op.drop_constraint('goods_received_notes_received_by_id_fkey', 'goods_received_notes', type_='foreignkey')
    op.drop_constraint('goods_received_notes_approved_by_id_fkey', 'goods_received_notes', type_='foreignkey')
    op.drop_constraint('goods_received_notes_received_into_store_location_id_fkey', 'goods_received_notes', type_='foreignkey')
    op.create_foreign_key(None, 'goods_received_notes', 'users', ['received_by_id'], ['id'])
    op.create_foreign_key(None, 'goods_received_notes', 'stock_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'goods_received_notes', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(None, 'goods_received_notes', 'store_locations', ['received_into_store_location_id'], ['id'])
    op.drop_constraint('income_categories_name_key', 'income_categories', type_='unique')
    op.create_index(op.f('ix_income_categories_id'), 'income_categories', ['id'], unique=False)
    op.alter_column('incomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    op.alter_column('module_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('module_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_callbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_payment_callbacks_status'), 'payment_callbacks', ['status'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.drop_index('ix_permissions_code', table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.alter_column('plan_modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_catalog', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_product_catalog_id'), 'product_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_reference_items_id'), 'reference_items', ['id'], unique=False)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('slaughter_byproducts', 'store_location_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_slaughter_byproducts_stock_item_id', table_name='slaughter_byproducts')
    op.drop_index('ix_slaughter_byproducts_store_location_id', table_name='slaughter_byproducts')
    op.alter_column('slaughter_records', 'waste_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'condemned_birds_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('slaughter_records', 'blood_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'feathers_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'offal_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'head_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'feet_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'reusable_byproducts_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('stock_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_stock_items_id'), 'stock_items', ['id'], unique=False)
    op.alter_column('stock_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_locations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('store_locations_id_seq'::regclass)"))
    op.alter_column('store_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_store_locations_code', 'store_locations', type_='unique')
    op.drop_constraint('uq_store_locations_name', 'store_locations', type_='unique')
    op.drop_index('ix_store_locations_code', table_name='store_locations')
    op.create_index(op.f('ix_store_locations_code'), 'store_locations', ['code'], unique=True)
    op.drop_index('ix_store_locations_name', table_name='store_locations')
    op.create_index(op.f('ix_store_locations_name'), 'store_locations', ['name'], unique=True)
    op.alter_column('subscription_history', 'changed_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('system_configs_key_key', 'system_configs', type_='unique')
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.alter_column('tenant_domain_request_messages', 'sender_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('tenant_domain_requests', 'requested_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('tenant_domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_tenant_domains_host', 'tenant_domains', type_='unique')
    op.drop_index('ix_tenant_domains_host', table_name='tenant_domains')
    op.create_index(op.f('ix_tenant_domains_host'), 'tenant_domains', ['host'], unique=True)
    op.alter_column('tenant_module_request_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_module_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_module_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('tenant_modules_tenant_id_fkey', 'tenant_modules', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_modules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('tenants_name_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index('ix_user_permissions_user_id', table_name='user_permissions')
    op.add_column('vaccination_logs', sa.Column('vaccine_item_id', sa.Integer(), nullable=True))
    op.add_column('vaccination_logs', sa.Column('dosage_per_bird', sa.Float(), nullable=True))
    op.add_column('vaccination_logs', sa.Column('total_dosage', sa.Float(), nullable=True))
    op.add_column('vaccination_logs', sa.Column('quantity_used', sa.Float(), nullable=True))
    op.add_column('vaccination_logs', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('vaccination_logs', sa.Column('birds_vaccinated', sa.Integer(), nullable=True))
    op.add_column('vaccination_logs', sa.Column('administered_by_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'vaccination_logs', 'users', ['administered_by_id'], ['id'])
    op.create_foreign_key(None, 'vaccination_logs', 'stock_items', ['vaccine_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccination_logs', type_='foreignkey')
    op.drop_constraint(None, 'vaccination_logs', type_='foreignkey')
    op.drop_column('vaccination_logs', 'administered_by_id')
    op.drop_column('vaccination_logs', 'birds_vaccinated')
    op.drop_column('vaccination_logs', 'unit')
    op.drop_column('vaccination_logs', 'quantity_used')
    op.drop_column('vaccination_logs', 'total_dosage')
    op.drop_column('vaccination_logs', 'dosage_per_bird')
    op.drop_column('vaccination_logs', 'vaccine_item_id')
    op.create_index('ix_user_permissions_user_id', 'user_permissions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False)
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'])
    op.create_unique_constraint('tenants_name_key', 'tenants', ['name'])
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'tenant_modules', type_='foreignkey')
    op.create_foreign_key('tenant_modules_tenant_id_fkey', 'tenant_modules', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenant_modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_module_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_module_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_module_request_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tenant_domains_host'), table_name='tenant_domains')
    op.create_index('ix_tenant_domains_host', 'tenant_domains', ['host'], unique=False)
    op.create_unique_constraint('uq_tenant_domains_host', 'tenant_domains', ['host'])
    op.alter_column('tenant_domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_domain_requests', 'requested_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('tenant_domain_request_messages', 'sender_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.create_unique_constraint('system_configs_key_key', 'system_configs', ['key'])
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscription_history', 'changed_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_store_locations_name'), table_name='store_locations')
    op.create_index('ix_store_locations_name', 'store_locations', ['name'], unique=False)
    op.drop_index(op.f('ix_store_locations_code'), table_name='store_locations')
    op.create_index('ix_store_locations_code', 'store_locations', ['code'], unique=False)
    op.create_unique_constraint('uq_store_locations_name', 'store_locations', ['name'])
    op.create_unique_constraint('uq_store_locations_code', 'store_locations', ['code'])
    op.alter_column('store_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_locations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('store_locations_id_seq'::regclass)"))
    op.alter_column('stock_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_stock_items_id'), table_name='stock_items')
    op.alter_column('stock_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('slaughter_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('slaughter_records', 'reusable_byproducts_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'feet_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'head_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'offal_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'feathers_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'blood_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('slaughter_records', 'condemned_birds_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('slaughter_records', 'waste_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.create_index('ix_slaughter_byproducts_store_location_id', 'slaughter_byproducts', ['store_location_id'], unique=False)
    op.create_index('ix_slaughter_byproducts_stock_item_id', 'slaughter_byproducts', ['stock_item_id'], unique=False)
    op.alter_column('slaughter_byproducts', 'store_location_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_index(op.f('ix_reference_items_id'), table_name='reference_items')
    op.drop_index(op.f('ix_product_catalog_id'), table_name='product_catalog')
    op.alter_column('product_catalog', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plan_modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index('ix_permissions_code', 'permissions', ['code'], unique=False)
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payment_callbacks_status'), table_name='payment_callbacks')
    op.alter_column('payment_callbacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('module_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('module_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_income_categories_id'), table_name='income_categories')
    op.create_unique_constraint('income_categories_name_key', 'income_categories', ['name'])
    op.drop_constraint(None, 'goods_received_notes', type_='foreignkey')
    op.drop_constraint(None, 'goods_received_notes', type_='foreignkey')
    op.drop_constraint(None, 'goods_received_notes', type_='foreignkey')
    op.drop_constraint(None, 'goods_received_notes', type_='foreignkey')
    op.create_foreign_key('goods_received_notes_received_into_store_location_id_fkey', 'goods_received_notes', 'store_locations', ['received_into_store_location_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('goods_received_notes_approved_by_id_fkey', 'goods_received_notes', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('goods_received_notes_received_by_id_fkey', 'goods_received_notes', 'users', ['received_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('goods_received_notes_item_id_fkey', 'goods_received_notes', 'stock_items', ['item_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_goods_received_notes_grn_number'), table_name='goods_received_notes')
    op.create_index('ix_goods_received_notes_grn_number', 'goods_received_notes', ['grn_number'], unique=False)
    op.create_unique_constraint('uq_grn_number', 'goods_received_notes', ['grn_number'])
    op.alter_column('goods_received_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goods_received_notes', 'approved_by_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('goods_received_notes', 'received_by_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'received_into_store_location_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_received_notes', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'goods_issue_vouchers', type_='foreignkey')
    op.drop_constraint(None, 'goods_issue_vouchers', type_='foreignkey')
    op.create_foreign_key('goods_issue_vouchers_item_id_fkey', 'goods_issue_vouchers', 'stock_items', ['item_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('goods_issue_vouchers_issued_by_id_fkey', 'goods_issue_vouchers', 'users', ['issued_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('goods_issue_vouchers_approved_by_id_fkey', 'goods_issue_vouchers', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('goods_issue_vouchers_from_store_location_id_fkey', 'goods_issue_vouchers', 'store_locations', ['from_store_location_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_goods_issue_vouchers_giv_number'), table_name='goods_issue_vouchers')
    op.create_index('ix_goods_issue_vouchers_giv_number', 'goods_issue_vouchers', ['giv_number'], unique=False)
    op.create_unique_constraint('uq_giv_number', 'goods_issue_vouchers', ['giv_number'])
    op.alter_column('goods_issue_vouchers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goods_issue_vouchers', 'approved_by_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('goods_issue_vouchers', 'issued_by_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'from_store_location_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('goods_issue_vouchers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.create_unique_constraint('expense_categories_name_key', 'expense_categories', ['name'])
    op.add_column('egg_production_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('egg_production_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_reminders_status'), table_name='document_reminders')
    op.drop_index(op.f('ix_document_reminders_document_id'), table_name='document_reminders')
    op.alter_column('document_reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_delivery_notes_id'), table_name='delivery_notes')
    op.create_index('ix_delivery_notes_status', 'delivery_notes', ['status'], unique=False)
    op.create_index('ix_delivery_notes_order_id', 'delivery_notes', ['order_id'], unique=False)
    op.create_index('ix_delivery_notes_customer_id', 'delivery_notes', ['customer_id'], unique=False)
    op.alter_column('delivery_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('delivery_notes', 'status',
               existing_type=sa.Enum('pending', 'in_transit', 'delivered', 'cancelled', name='deliverystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_compliance_documents_document_type'), table_name='compliance_documents')
    op.alter_column('compliance_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_billing_invoices_request_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_invoice_number'), table_name='billing_invoices')
    op.create_unique_constraint('uq_billing_invoices_invoice_number', 'billing_invoices', ['invoice_number'])
    op.create_unique_constraint('billing_invoices_request_id_key', 'billing_invoices', ['request_id'])
    op.alter_column('billing_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('affiliates', 'approved_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_safety_inspection_items_id'), table_name='safety_inspection_items')
    op.drop_table('safety_inspection_items')
    op.drop_index(op.f('ix_medication_administrations_medicine_item_id'), table_name='medication_administrations')
    op.drop_index(op.f('ix_medication_administrations_batch_id'), table_name='medication_administrations')
    op.drop_table('medication_administrations')
    op.drop_index(op.f('ix_journal_lines_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_invoice_balance_reminders_status'), table_name='invoice_balance_reminders')
    op.drop_index(op.f('ix_invoice_balance_reminders_scheduled_for'), table_name='invoice_balance_reminders')
    op.drop_index(op.f('ix_invoice_balance_reminders_reminder_type'), table_name='invoice_balance_reminders')
    op.drop_index(op.f('ix_invoice_balance_reminders_invoice_id'), table_name='invoice_balance_reminders')
    op.drop_index(op.f('ix_invoice_balance_reminders_id'), table_name='invoice_balance_reminders')
    op.drop_index(op.f('ix_invoice_balance_reminders_customer_id'), table_name='invoice_balance_reminders')
    op.drop_table('invoice_balance_reminders')
    op.drop_index(op.f('ix_safety_inspections_inspection_number'), table_name='safety_inspections')
    op.drop_index(op.f('ix_safety_inspections_id'), table_name='safety_inspections')
    op.drop_table('safety_inspections')
    op.drop_index(op.f('ix_opening_balances_tenant_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_fiscal_year_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_account_id'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_master_data_requests_status'), table_name='master_data_requests')
    op.drop_index(op.f('ix_master_data_requests_request_type'), table_name='master_data_requests')
    op.drop_index(op.f('ix_master_data_requests_id'), table_name='master_data_requests')
    op.drop_table('master_data_requests')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_incident_reports_incident_number'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_feed_production_batches_batch_number'), table_name='feed_production_batches')
    op.drop_table('feed_production_batches')
    op.drop_index(op.f('ix_feed_formulation_ingredients_formulation_id'), table_name='feed_formulation_ingredients')
    op.drop_table('feed_formulation_ingredients')
    op.drop_index(op.f('ix_corrective_actions_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_template_accounts_template_id'), table_name='template_accounts')
    op.drop_index(op.f('ix_template_accounts_id'), table_name='template_accounts')
    op.drop_table('template_accounts')
    op.drop_index(op.f('ix_stock_transfers_reference_number'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_fiscal_years_tenant_id'), table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_feed_formulations_stage'), table_name='feed_formulations')
    op.drop_index(op.f('ix_feed_formulations_name'), table_name='feed_formulations')
    op.drop_table('feed_formulations')
    op.drop_index(op.f('ix_account_templates_name'), table_name='account_templates')
    op.drop_index(op.f('ix_account_templates_id'), table_name='account_templates')
    op.drop_table('account_templates')
    # ### end Alembic commands ###
