"""
Default SaaS catalog for modules, plans, and pricing.
"""

DEFAULT_MODULES = [
    {"key": "dashboard", "name": "Dashboard", "category": "dashboard", "description": "Overview, tasks, and alerts", "is_core": True},
    {"key": "farm_profile", "name": "Farm Profile", "category": "farm_setup", "description": "Tenant farm profile and settings", "is_core": True},
    {"key": "houses", "name": "Houses / Pens", "category": "farm_setup", "description": "Farm housing and pen structure", "is_core": True},
    {"key": "breeds", "name": "Breeds", "category": "farm_setup", "description": "Bird breed master data", "is_core": False},
    {"key": "suppliers", "name": "Suppliers", "category": "farm_setup", "description": "Suppliers and procurement contacts", "is_core": False},
    {"key": "customers", "name": "Customers", "category": "sales", "description": "Customer directory and balances", "is_core": False},
    {"key": "batches", "name": "Batches / Flocks", "category": "batches", "description": "Batch registration and monitoring", "is_core": True},
    {"key": "batch_performance", "name": "Batch Performance", "category": "batches", "description": "Batch KPIs and performance analysis", "is_core": False},
    {"key": "egg_production", "name": "Egg Collection", "category": "daily_operations", "description": "Daily egg collection and rate tracking", "is_core": True},
    {"key": "feed_consumption", "name": "Feed Usage", "category": "daily_operations", "description": "Feed consumption and usage logs", "is_core": True},
    {"key": "mortality", "name": "Mortality", "category": "daily_operations", "description": "Mortality records and reasons", "is_core": True},
    {"key": "vaccination", "name": "Vaccination", "category": "daily_operations", "description": "Vaccination schedule and logs", "is_core": False},
    {"key": "medication", "name": "Medication", "category": "daily_operations", "description": "Medication records", "is_core": False},
    {"key": "growth_tracking", "name": "Growth / Weight Checks", "category": "daily_operations", "description": "Weight checks and growth trends", "is_core": False},
    {"key": "health_observations", "name": "Health Observations", "category": "daily_operations", "description": "Health notes and welfare issues", "is_core": False},
    {"key": "feed_stock", "name": "Feed Stock", "category": "inventory", "description": "Feed inventory", "is_core": True},
    {"key": "feed_purchases", "name": "Feed Purchases", "category": "feed", "description": "Feed procurement and receiving", "is_core": False},
    {"key": "feed_suppliers", "name": "Feed Suppliers", "category": "feed", "description": "Feed supplier tracking", "is_core": False},
    {"key": "feed_wastage", "name": "Feed Wastage", "category": "feed", "description": "Feed loss and wastage tracking", "is_core": False},
    {"key": "inventory_items", "name": "Inventory Items", "category": "inventory", "description": "General stock records", "is_core": False},
    {"key": "inventory_movements", "name": "Stock Movements", "category": "inventory", "description": "Stock movements and transfers", "is_core": False},
    {"key": "medicine_supplies", "name": "Medicine Stock", "category": "inventory", "description": "Medicine and supplies stock", "is_core": False},
    {"key": "egg_stock", "name": "Egg Stock", "category": "inventory", "description": "Egg inventory", "is_core": False},
    {"key": "meat_stock", "name": "Meat Stock", "category": "inventory", "description": "Processed meat inventory", "is_core": False},
    {"key": "packaging_stock", "name": "Packaging Stock", "category": "inventory", "description": "Packaging inventory", "is_core": False},
    {"key": "byproduct_stock", "name": "Byproduct Stock", "category": "inventory", "description": "Byproduct stock", "is_core": False},
    {"key": "low_stock_alerts", "name": "Low Stock Alerts", "category": "inventory", "description": "Inventory alerting", "is_core": False},
    {"key": "slaughter_planning", "name": "Slaughter Planning", "category": "slaughter", "description": "Processing schedules and preparation", "is_core": False},
    {"key": "slaughter_records", "name": "Slaughter Records", "category": "slaughter", "description": "Slaughter transactions and yields", "is_core": False},
    {"key": "slaughter_outputs", "name": "Slaughter Outputs", "category": "slaughter", "description": "Processed output inventory", "is_core": False},
    {"key": "slaughter_cut_parts", "name": "Cut Parts", "category": "slaughter", "description": "Detailed cut part capture", "is_core": False},
    {"key": "slaughter_byproducts", "name": "Byproducts", "category": "slaughter", "description": "Byproduct capture and disposition", "is_core": False},
    {"key": "yield_analysis", "name": "Yield Analysis", "category": "slaughter", "description": "Yield and processing loss reporting", "is_core": False},
    {"key": "sales_orders", "name": "Orders", "category": "sales", "description": "Sales orders", "is_core": False},
    {"key": "invoices", "name": "Invoices", "category": "sales", "description": "Invoicing", "is_core": False},
    {"key": "payments", "name": "Payments", "category": "sales", "description": "Payment collection", "is_core": False},
    {"key": "balances", "name": "Balances", "category": "sales", "description": "Customer balances", "is_core": False},
    {"key": "expenses", "name": "Expenses", "category": "finance", "description": "Expense tracking", "is_core": False},
    {"key": "income", "name": "Income", "category": "finance", "description": "Income tracking", "is_core": False},
    {"key": "batch_costing", "name": "Batch Costing", "category": "finance", "description": "Batch cost allocation", "is_core": False},
    {"key": "profit_loss", "name": "Profit & Loss", "category": "finance", "description": "Profit and loss reporting", "is_core": False},
    {"key": "cash_flow", "name": "Cash Flow", "category": "finance", "description": "Cash flow reporting", "is_core": False},
    {"key": "compliance_documents", "name": "Compliance Documents", "category": "compliance", "description": "Licences, permits, and tax documents", "is_core": False},
    {"key": "compliance_alerts", "name": "Compliance Alerts", "category": "compliance", "description": "Expiry and renewal alerts", "is_core": False},
    {"key": "reports", "name": "Reports", "category": "reports", "description": "Operational and management reports", "is_core": True},
    {"key": "users", "name": "Users", "category": "administration", "description": "User administration", "is_core": False},
    {"key": "settings", "name": "Settings", "category": "administration", "description": "Tenant settings", "is_core": False},
]

DEFAULT_PLANS = [
    {"code": "basic", "name": "Core", "description": "Core farm operation modules", "billing_cycle": "monthly", "is_custom": False},
    {"code": "standard", "name": "Standard", "description": "Operational, feed, inventory, and sales modules", "billing_cycle": "monthly", "is_custom": False},
    {"code": "premium", "name": "Premium", "description": "Full operational, compliance, finance, and admin suite", "billing_cycle": "monthly", "is_custom": False},
    {"code": "custom", "name": "Custom", "description": "Developer-admin configured package", "billing_cycle": "monthly", "is_custom": True},
]

DEFAULT_PLAN_MODULES = {
    "basic": [
        "dashboard",
        "farm_profile",
        "houses",
        "batches",
        "egg_production",
        "feed_stock",
        "feed_consumption",
        "mortality",
        "reports",
    ],
    "standard": [
        "dashboard",
        "farm_profile",
        "houses",
        "batches",
        "egg_production",
        "feed_stock",
        "feed_consumption",
        "mortality",
        "vaccination",
        "medication",
        "growth_tracking",
        "feed_purchases",
        "feed_suppliers",
        "inventory_items",
        "inventory_movements",
        "customers",
        "sales_orders",
        "invoices",
        "payments",
        "slaughter_records",
        "slaughter_outputs",
        "reports",
    ],
    "premium": [module["key"] for module in DEFAULT_MODULES if module["key"] not in {"balances"}],
    "custom": [],
}

DEFAULT_MODULE_PRICES = [
    {"module_key": "slaughter_records", "billing_cycle": "monthly", "price": 150000, "currency": "UGX", "notes": "Advanced processing module"},
    {"module_key": "compliance_documents", "billing_cycle": "monthly", "price": 100000, "currency": "UGX", "notes": "Compliance and reminders"},
    {"module_key": "profit_loss", "billing_cycle": "monthly", "price": 120000, "currency": "UGX", "notes": "Advanced finance reporting"},
]

